repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, perf, deps, chore, refactor, test, build, ci, docs, style, revert]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/aolieman/yaml-schema
    rev: 29c5dbcc376159f8d2950ef030794e6477d2d5cb
    hooks:
      - id: ys
        name: Validate Project Data
        args: ["-f", "pg_atlas/data/schema-override-project.yml"]
        files: ^pg_atlas/data/projects/.*\.yml$
