name: pg-atlas-backend
region: ams3
services:
  - name: api
    github:
      repo: SCF-Public-Goods-Maintenance/pg-atlas-backend
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PG_ATLAS_API_URL
        scope: RUN_TIME
        value: "${APP_URL}"
